#!/usr/bin/env python3
"""Generate shapes.h for the claim-1 sweep.

A "shape" is a road: a straight-line arrangement of ops drawn from a
small FIXED vocabulary (MACHINE.md layer 3: arrangement, not material).
Every dispatch variant in the harness executes the *same* per-shape
computation; only the dispatch mechanism differs. Generation is fully
deterministic from (seed, N, L).

Emitted per shape k:
  shape_body_k   - static inline body (the arrangement itself)
  shape_fn_k     - noinline single-value fn (target for per-element routing)
  shape_batch_k  - noinline batch fn: the road's pre-staged straight-line
                   firing plan with value slots (MACHINE.md layer 1/4)
Plus:
  dispatch_switch - idiomatic branchy baseline (dense switch; gcc emits
                    a jump table = one indirect branch per element)
  dispatch_chain  - branchy baseline #2: binary comparison tree over the
                    tag (what compilers emit for sparse dispatch;
                    ~log2(N) conditional branches per element)
  SHAPE_FN[], SHAPE_BATCH[] - road tables indexed by tag
"""
import sys
import random

# The fixed, vetted vocabulary. Data may only ARRANGE these
# (MACHINE.md safety condition); a shape is a sequence of them.
def gen_op(rng):
    kind = rng.randrange(6)
    if kind == 0:
        return f"x += 0x{rng.getrandbits(64):016x}ULL;"
    if kind == 1:
        return f"x ^= 0x{rng.getrandbits(64):016x}ULL;"
    if kind == 2:
        return f"x *= 0x{rng.getrandbits(64) | 1:016x}ULL;"
    if kind == 3:
        r = rng.randrange(1, 64)
        return f"x = (x << {r}) | (x >> {64 - r});"
    if kind == 4:
        s = rng.randrange(1, 64)
        return f"x ^= x >> {s};"
    s = rng.randrange(1, 32)
    return f"x += x << {s};"


def gen_chain(lo, hi, indent):
    """Binary comparison tree over tag in [lo, hi)."""
    pad = "    " * indent
    if hi - lo == 1:
        return f"{pad}return shape_body_{lo}(x);\n"
    mid = (lo + hi) // 2
    s = f"{pad}if (tag < {mid}u) {{\n"
    s += gen_chain(lo, mid, indent + 1)
    s += f"{pad}}} else {{\n"
    s += gen_chain(mid, hi, indent + 1)
    s += f"{pad}}}\n"
    return s


def main():
    n, length, seed, out_path = (
        int(sys.argv[1]), int(sys.argv[2]), int(sys.argv[3]), sys.argv[4])
    w = []
    w.append("/* generated by gen_shapes.py - do not edit */\n")
    w.append(f"#define NSHAPES {n}u\n#define SHAPE_OPS {length}\n")
    w.append(f"#define SHAPE_SEED {seed}\n\n")

    for k in range(n):
        rng = random.Random((seed << 20) ^ k)
        body = "\n    ".join(gen_op(rng) for _ in range(length))
        w.append(
            f"static inline uint64_t shape_body_{k}(uint64_t x) {{\n"
            f"    {body}\n    return x;\n}}\n")

    for k in range(n):
        w.append(
            f"static uint64_t __attribute__((noinline)) shape_fn_{k}"
            f"(uint64_t x) {{ return shape_body_{k}(x); }}\n")

    # The firing plan: whole road fires over its batch, straight-line,
    # one perfectly-predictable loop branch. Values land at their
    # original stream index (guarantee parity with in-order variants).
    for k in range(n):
        w.append(
            f"static void __attribute__((noinline)) shape_batch_{k}"
            f"(const rec_t *r, uint32_t cnt, uint64_t *out) {{\n"
            f"    for (uint32_t i = 0; i < cnt; i++)\n"
            f"        out[r[i].idx] = shape_body_{k}(r[i].val);\n}}\n")

    w.append("\nstatic uint64_t (*const SHAPE_FN[NSHAPES])(uint64_t) = {\n")
    w.append(",\n".join(f"    shape_fn_{k}" for k in range(n)))
    w.append("\n};\n")
    w.append(
        "static void (*const SHAPE_BATCH[NSHAPES])"
        "(const rec_t *, uint32_t, uint64_t *) = {\n")
    w.append(",\n".join(f"    shape_batch_{k}" for k in range(n)))
    w.append("\n};\n\n")

    # Dispatchers are force-inlined into the measurement loop: the
    # branchy baseline pays only its branches, never call overhead.
    w.append(
        "static inline __attribute__((always_inline)) uint64_t "
        "dispatch_switch(uint32_t tag, uint64_t x) {\n    switch (tag) {\n")
    for k in range(n):
        w.append(f"    case {k}u: return shape_body_{k}(x);\n")
    w.append("    default: return 0;\n    }\n}\n\n")

    w.append(
        "static inline __attribute__((always_inline)) uint64_t "
        "dispatch_chain(uint32_t tag, uint64_t x) {\n")
    w.append(gen_chain(0, n, 1))
    w.append("}\n")

    with open(out_path, "w") as f:
        f.write("".join(w))


if __name__ == "__main__":
    main()
