#!/usr/bin/env python3
"""Per-syscall-kind enrichment kernels, ONE definition, TWO emissions:
  - nmo_node tables (the engine's arrangements)
  - inline C handlers + a dispatch switch (the idiomatic baseline)
Both compile from the same op list, so any divergence is a bug the
bench's parity check catches, not a benchmark artifact.

The kernel per kind is a realistic small telemetry enrichment: errno
detection (a genuine value-fork -> SELECT), a kind-specific size
bucket, and a kind-specific mix/sample hash. 10-16 vocabulary ops,
constants varying per kind. The TRAFFIC is real; these kernels are the
processing we impose on it, and they are stated as such.
"""
import json
import random
import sys

BIN = { "ADD": "l + r", "SUB": "l - r", "MUL": "l * r",
        "AND": "l & r", "OR": "l | r", "XOR": "l ^ r",
        "SHL": "l << (r & 63)", "SHR": "l >> (r & 63)",
        "ROTL": "(l << (r & 63)) | (l >> ((64 - (r & 63)) & 63))",
        "EQ": "(uint64_t)(l == r)", "LT": "(uint64_t)(l < r)",
        "MIN": "l < r ? l : r", "MAX": "l > r ? l : r" }


def kernel(tag, rng):
    """returns list of nodes: (op, a, b, c, imm); node 0 is INPUT"""
    ns = [("INPUT", 0, 0, 0, 0)]

    def const(v):
        ns.append(("CONST", 0, 0, 0, v))
        return len(ns) - 1

    def op(o, a, b, c=0):
        ns.append((o, a, b, c, 0))
        return len(ns) - 1

    x = 0
    # errno range detection: ret values in [-4095, -1] mean error
    e = op("LT", const(0xFFFFFFFFFFFFF000), x)
    # kind-specific size bucket
    b = op("SHR", x, const(rng.randrange(3, 12)))
    b = op("AND", b, const((1 << rng.randrange(4, 8)) - 1))
    # kind-specific mix (sampling hash), depth varies per kind
    m = op("MUL", x, const(rng.getrandbits(64) | 1))
    for _ in range(rng.randrange(1, 4)):
        m = op("XOR", m, const(rng.getrandbits(64)))
        m = op("ROTL", m, const(rng.randrange(1, 63)))
    m = op("ADD", m, b)
    # error path: tag the value with a kind-specific error constant
    err = op("XOR", x, const(rng.getrandbits(64) | (tag + 1)))
    out = op("SELECT", e, err, m)
    return ns, out


def emit_expr(f, k, ns, out):
    f.write(f"static inline uint64_t handler_{k}(uint64_t x) {{\n")
    for i, (o, a, b, c, imm) in enumerate(ns):
        if o == "INPUT":
            f.write(f"    uint64_t v{i} = x;\n")
        elif o == "CONST":
            f.write(f"    uint64_t v{i} = 0x{imm:016x}ULL;\n")
        elif o == "SELECT":
            f.write(f"    uint64_t v{i} = v{a} ? v{b} : v{c};\n")
        else:
            f.write(f"    uint64_t v{i}; {{ uint64_t l = v{a}, r = v{b};"
                    f" v{i} = ({BIN[o]}); }}\n")
    f.write(f"    return v{out};\n}}\n")


def main():
    stats_path, out_path = sys.argv[1], sys.argv[2]
    ntags = len(json.load(open(stats_path))["tag_names"])
    kernels = [kernel(t, random.Random(0xC1A140 ^ t)) for t in range(ntags)]

    with open(out_path, "w") as f:
        f.write("/* generated by gen.py - do not edit */\n")
        f.write(f"#define NTAGS {ntags}\n\n")
        for k, (ns, out) in enumerate(kernels):
            emit_expr(f, k, ns, out)

        f.write("\nstatic inline __attribute__((always_inline)) uint64_t "
                "dispatch(uint32_t tag, uint64_t x) {\n    switch (tag) {\n")
        for k in range(ntags):
            f.write(f"    case {k}u: return handler_{k}(x);\n")
        f.write("    default: return 0;\n    }\n}\n\n")

        for k, (ns, out) in enumerate(kernels):
            f.write(f"static const nmo_node NODES_{k}[] = {{\n")
            for (o, a, b, c, imm) in ns:
                f.write(f"    {{ NMO_OP_{o}, {a}, {b}, {c}, "
                        f"0x{imm:016x}ULL }},\n")
            f.write("};\n")
        f.write("\nstatic const struct { const nmo_node *nodes;"
                " uint16_t n, exit; } SHAPES[NTAGS] = {\n")
        for k, (ns, out) in enumerate(kernels):
            f.write(f"    {{ NODES_{k}, {len(ns)}, {out} }},\n")
        f.write("};\n")
        f.write(
            "\nstatic void build_arrangement(uint32_t tag,"
            " nmo_arrangement *a) {\n"
            "    memset(a, 0, sizeof(*a));\n"
            "    a->tag = tag;\n"
            "    a->nnodes = SHAPES[tag].n;\n"
            "    a->nexits = 1;\n"
            "    a->exits[0] = SHAPES[tag].exit;\n"
            "    memcpy(a->nodes, SHAPES[tag].nodes,\n"
            "           SHAPES[tag].n * sizeof(nmo_node));\n"
            "}\n")
    print(f"emitted {ntags} kernels to {out_path}")


if __name__ == "__main__":
    main()
